#!/bin/bash
if [ -e ~/.conkyrc ]; then
  echo "Creating backup file for ~/.conkyrc at ~/.conkyrc.bak "
  cat ~/.conkyrc > ~/.conkyrc.bak
  echo "Updating ~/.conkyrc with aqua theme"
fi
cat conkyrc_aqua > ~/.conkyrc
echo "Completed."
